name: Deploy to Netlify

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: "npm"

            - name: Install Netlify
              run: npm install netlify-cli@latest -g

            - name: Install Dependencies
              run: npm ci

            - name: Build Project
              run: npm run build

            - name: Deploy to Netlify
              id: netlify_deploy
              run: |
                netlify deploy \
                  --dir dist \
                  --site ${{ secrets.NETLIFY_SITE_ID }} \
                  --auth ${{ secrets.NETLIFY_API_TOKEN }}
